### ISSUE TITLE
Uploading to esp-wrover-kit board

### ISSUE THREAD

**Issue by iamandymcinnes** [vitotai/BrewPiLess#253]
Hi

I'm new to using platformio but am struggling to upload to an esp-wrover-kit board. I've updated the board on the esp32 profile to esp-wrover-kit and I can see my device being detected on COM13. I've also checked the drivers (i'm on windows 10) and it is correctly detecting the board in device manager with latest drivers (Silicon Labs CP210x USB to UART Bridge).

However when I select the upload option under the esp32 profile, I get the following error:

> Building .pio\build\esp32\firmware.bin
Checking size .pio\build\esp32\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  15.4% (used 50304 bytes from 327680 bytes)
Flash: [========= ]  89.3% (used 1171090 bytes from 1310720 bytes)
esptool.py v2.6
Configuring upload protocol...
AVAILABLE: esp-prog, espota, esptool, ftdi, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Use manually specified: /dev/cu.SLAB_USBtoUART
Uploading .pio\build\esp32\firmware.bin
esptool.py v2.6
Serial port /dev/cu.SLAB_USBtoUART
Traceback (most recent call last):
  File "C:\Users\mcinnesa\.platformio\packages\tool-esptoolpy\esptool.py", line 2959, in <module>
    _main()
  File "C:\Users\mcinnesa\.platformio\packages\tool-esptoolpy\esptool.py", line 2952, in _main
    main()
  File "C:\Users\mcinnesa\.platformio\packages\tool-esptoolpy\esptool.py", line 2652, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "C:\Users\mcinnesa\.platformio\packages\tool-esptoolpy\esptool.py", line 222, in __init__
    self._port = serial.serial_for_url(port)
  File "c:\users\mcinnesa\.platformio\penv\lib\site-packages\serial\__init__.py", line 88, in serial_for_url
    instance.open()
  File "c:\users\mcinnesa\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port '/dev/cu.SLAB_USBtoUART': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

**Comment by allthepies** [comment]
Have you tried commenting out the upload_port setting in platformio.ini and letting the uploaded autodetect ?
/dev/cu.SLAB_USBtoUART is a Mac/Linux device path, no good for windows.
