### ISSUE TITLE
Cannot Build esp32 with PlatformIO

### ISSUE THREAD

**Issue by tomohulk** [vitotai/BrewPiLess#267]
I can build every other env besides the esp32, which is the one I need.  when I run the build task I get the following error:

```
Traceback (most recent call last):
  File "/Users/thomas/.platformio/packages/tool-esptoolpy/esptool.py", line 57, in <module>
    import serial.tools.list_ports as list_ports
  File "/Users/thomas/.platformio/penv/lib/python3.8/site-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/Users/thomas/.platformio/penv/lib/python3.8/site-packages/serial/tools/list_ports_posix.py", line 31, in <module>
    from serial.tools.list_ports_osx import comports
  File "/Users/thomas/.platformio/penv/lib/python3.8/site-packages/serial/tools/list_ports_osx.py", line 32, in <module>
    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, "kIOMasterPortDefault")
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
*** [.pio/build/esp32/firmware.bin] Error 1
```

I can see the board is connecting in PlatformIO, any help would be appreciated.  thanks!

I am running OS X Big Sur (beta), could that have something to do with it?

**Comment by tomohulk** [comment]
it does appear this is an issue with Big Sur and not with your code/install procedure, so I am going to close this.

https://github.com/espressif/esptool/issues/540
